image_data: 'Morpho-MNIST'

meta_data:
  causal_mech: 'tanh'
  n_samples: 1024
  d: 3
  s0: 3
  graph_type: 'ER'
  gam_scale: 3.0
  noise_dist: 'gauss'

notears:
  use_notears: false
  lambda1: 0.1
  w_threshold: 0.3

carefl:
  net_class: 'mlp4'
  nh: 100
  prior_dist: 'normal'
  scale_shift_base: false

training:
  epochs: 200
  batch_size: 128

